-- MySQL Script generated by MySQL Workbench
-- 08/05/16 18:33:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payments` DEFAULT CHARACTER SET utf8 ;
USE `payments` ;

-- -----------------------------------------------------
-- Table `payments`.`Commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Commands` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COMMAND` VARCHAR(45) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `COMMAND_UNIQUE` (`COMMAND` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`User_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`User_Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`User_Role_Commands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`User_Role_Commands` (
  `Commands_ID` INT NOT NULL,
  `Ueser_Roles_id` INT NOT NULL,
  PRIMARY KEY (`Commands_ID`, `Ueser_Roles_id`),
  INDEX `fk_Commands_has_Ueser_Roles_Ueser_Roles1_idx` (`Ueser_Roles_id` ASC),
  INDEX `fk_Commands_has_Ueser_Roles_Commands_idx` (`Commands_ID` ASC),
  CONSTRAINT `fk_Commands_has_Ueser_Roles_Commands`
    FOREIGN KEY (`Commands_ID`)
    REFERENCES `payments`.`Commands` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commands_has_Ueser_Roles_Ueser_Roles1`
    FOREIGN KEY (`Ueser_Roles_id`)
    REFERENCES `payments`.`User_Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `personal_number` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `User_Roles_id` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `personal_number_UNIQUE` (`personal_number` ASC),
  INDEX `fk_Users_User_Roles1_idx` (`User_Roles_id` ASC),
  CONSTRAINT `fk_Users_User_Roles1`
    FOREIGN KEY (`User_Roles_id`)
    REFERENCES `payments`.`User_Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`Banks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Banks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `UNN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNN_UNIQUE` (`UNN` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`Agreements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Agreements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL,
  `valid_from_date` DATE NULL,
  `valid_to_date` DATE NULL,
  `Banks_id` INT NOT NULL,
  `Users_ID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Agreements_Banks1_idx` (`Banks_id` ASC),
  INDEX `fk_Agreements_Users1_idx` (`Users_ID` ASC),
  UNIQUE INDEX `uk_agreements` (`Banks_id` ASC, `number` ASC),
  CONSTRAINT `fk_Agreements_Banks1`
    FOREIGN KEY (`Banks_id`)
    REFERENCES `payments`.`Banks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agreements_Users1`
    FOREIGN KEY (`Users_ID`)
    REFERENCES `payments`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`Currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `mnemo_code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `currency_uk` (`mnemo_code` ASC, `code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`exchange_rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`exchange_rates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rate_date` DATE NOT NULL,
  `rate` FLOAT NOT NULL,
  `Currency_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exchange_rates_Curremcies1_idx` (`Currency_id` ASC),
  UNIQUE INDEX `exchange_rate_uk` (`Currency_id` ASC, `rate_date` ASC),
  CONSTRAINT `fk_exchange_rates_Curremcies1`
    FOREIGN KEY (`Currency_id`)
    REFERENCES `payments`.`Currencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `Currencies_id` INT NOT NULL,
  `Agreements_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_Accounts_Currencies1_idx` (`Currencies_id` ASC),
  INDEX `fk_Accounts_Agreements1_idx` (`Agreements_id` ASC),
  CONSTRAINT `fk_Accounts_Currencies1`
    FOREIGN KEY (`Currencies_id`)
    REFERENCES `payments`.`Currencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_Agreements1`
    FOREIGN KEY (`Agreements_id`)
    REFERENCES `payments`.`Agreements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payments`.`Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payments`.`Cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `valid_to_date` DATE NOT NULL,
  `Accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC),
  INDEX `fk_Cards_Accounts1_idx` (`Accounts_id` ASC),
  CONSTRAINT `fk_Cards_Accounts1`
    FOREIGN KEY (`Accounts_id`)
    REFERENCES `payments`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
